// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Animation : HardwiredObject {
		static Animation instance;

		static Animation() {
			instance = new Animation();
		}

		static public void Init() {
		}

		public static Animation Instance {
			get { return instance; }
		}

		protected Animation() : base(PowerObject.PowerObjectParent, "Animation", DragObject.Instance) {
		}
	}
}
