// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class DataWindow : HardwiredObject {
		static DataWindow instance;

		static DataWindow() {
			instance = new DataWindow();
		}

		static public void Init() {
		}

		public static DataWindow Instance {
			get { return instance; }
		}

		protected DataWindow() : base(PowerObject.PowerObjectParent, "DataWindow", DragObject.Instance) {
		}
	}
}
