// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class DatePicker : HardwiredObject {
		static DatePicker instance;

		static DatePicker() {
			instance = new DatePicker();
		}

		static public void Init() {
		}

		public static DatePicker Instance {
			get { return instance; }
		}

		protected DatePicker() : base(PowerObject.PowerObjectParent, "DatePicker", DragObject.Instance) {
		}
	}
}
