// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class DropDownPictureListbox : HardwiredObject {
		static DropDownPictureListbox instance;

		static DropDownPictureListbox() {
			instance = new DropDownPictureListbox();
		}

		static public void Init() {
		}

		public static DropDownPictureListbox Instance {
			get { return instance; }
		}

		protected DropDownPictureListbox() : base(PowerObject.PowerObjectParent, "DropDownPictureListbox", DropDownListbox.Instance) {
		}
	}
}
