// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class DropDownListbox : HardwiredObject {
		static DropDownListbox instance;

		static DropDownListbox() {
			instance = new DropDownListbox();
		}

		static public void Init() {
		}

		public static DropDownListbox Instance {
			get { return instance; }
		}

		protected DropDownListbox() : base(PowerObject.PowerObjectParent, "DropDownListbox", DragObject.Instance) {
		}
	}
}
