// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class EditMask : HardwiredObject {
		static EditMask instance;

		static EditMask() {
			instance = new EditMask();
		}

		static public void Init() {
		}

		public static EditMask Instance {
			get { return instance; }
		}

		protected EditMask() : base(PowerObject.PowerObjectParent, "EditMask", MultiLineEdit.Instance) {
		}
	}
}
