// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Graph : HardwiredObject {
		static Graph instance;

		static Graph() {
			instance = new Graph();
		}

		static public void Init() {
		}

		public static Graph Instance {
			get { return instance; }
		}

		protected Graph() : base(PowerObject.PowerObjectParent, "Graph", DragObject.Instance) {
		}
	}
}
