// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class HProgressBar : HardwiredObject {
		static HProgressBar instance;

		static HProgressBar() {
			instance = new HProgressBar();
		}

		static public void Init() {
		}

		public static HProgressBar Instance {
			get { return instance; }
		}

		protected HProgressBar() : base(PowerObject.PowerObjectParent, "HProgressBar", DragObject.Instance) {
		}
	}
}
