// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class HScrollBar : HardwiredObject {
		static HScrollBar instance;

		static HScrollBar() {
			instance = new HScrollBar();
		}

		static public void Init() {
		}

		public static HScrollBar Instance {
			get { return instance; }
		}

		protected HScrollBar() : base(PowerObject.PowerObjectParent, "HScrollBar", DragObject.Instance) {
		}
	}
}
