// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class ListBox : HardwiredObject {
		static ListBox instance;

		static ListBox() {
			instance = new ListBox();
		}

		static public void Init() {
		}

		public static ListBox Instance {
			get { return instance; }
		}

		protected ListBox() : base(PowerObject.PowerObjectParent, "ListBox", DragObject.Instance) {
		}
	}
}
