// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class ListView : HardwiredObject {
		static ListView instance;

		static ListView() {
			instance = new ListView();
		}

		static public void Init() {
		}

		public static ListView Instance {
			get { return instance; }
		}

		protected ListView() : base(PowerObject.PowerObjectParent, "ListView", DragObject.Instance) {
		}
	}
}
