// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class MdiClient : HardwiredObject {
		static MdiClient instance;

		static MdiClient() {
			instance = new MdiClient();
		}

		static public void Init() {
		}

		public static MdiClient Instance {
			get { return instance; }
		}

		protected MdiClient() : base(PowerObject.PowerObjectParent, "MdiClient", WindowObject.Instance) {
		}
	}
}
