// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Menu : HardwiredObject {
		static Menu instance;

		static Menu() {
			instance = new Menu();
		}

		static public void Init() {
		}

		public static Menu Instance {
			get { return instance; }
		}

		protected Menu() : base(PowerObject.PowerObjectParent, "Menu", GraphicObject.Instance) {
		}
	}
}
