// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class MenuCascade : HardwiredObject {
		static MenuCascade instance;

		static MenuCascade() {
			instance = new MenuCascade();
		}

		static public void Init() {
		}

		public static MenuCascade Instance {
			get { return instance; }
		}

		protected MenuCascade() : base(PowerObject.PowerObjectParent, "MenuCascade", Menu.Instance) {
		}
	}
}
