// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class MultiLineEdit : HardwiredObject {
		static MultiLineEdit instance;

		static MultiLineEdit() {
			instance = new MultiLineEdit();
		}

		static public void Init() {
		}

		public static MultiLineEdit Instance {
			get { return instance; }
		}

		protected MultiLineEdit() : base(PowerObject.PowerObjectParent, "MultiLineEdit", DragObject.Instance) {
		}
	}
}
