// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class OleControl : HardwiredObject {
		static OleControl instance;

		static OleControl() {
			instance = new OleControl();
		}

		static public void Init() {
		}

		public static OleControl Instance {
			get { return instance; }
		}

		protected OleControl() : base(PowerObject.PowerObjectParent, "OleControl", OMEmbeddedControl.Instance) {
		}
	}
}
