// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class OleCustomControl : HardwiredObject {
		static OleCustomControl instance;

		static OleCustomControl() {
			instance = new OleCustomControl();
		}

		static public void Init() {
		}

		public static OleCustomControl Instance {
			get { return instance; }
		}

		protected OleCustomControl() : base(PowerObject.PowerObjectParent, "OleCustomControl", OMCustomControl.Instance) {
		}
	}
}
