// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class OMControl : HardwiredObject {
		static OMControl instance;

		static OMControl() {
			instance = new OMControl();
		}

		static public void Init() {
		}

		public static OMControl Instance {
			get { return instance; }
		}

		protected OMControl() : base(PowerObject.PowerObjectParent, "OMControl", DragObject.Instance) {
		}
	}
}
