// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class OMEmbeddedControl : HardwiredObject {
		static OMEmbeddedControl instance;

		static OMEmbeddedControl() {
			instance = new OMEmbeddedControl();
		}

		static public void Init() {
		}

		public static OMEmbeddedControl Instance {
			get { return instance; }
		}

		protected OMEmbeddedControl() : base(PowerObject.PowerObjectParent, "OMEmbeddedControl", OMControl.Instance) {
		}
	}
}
