// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Oval : HardwiredObject {
		static Oval instance;

		static Oval() {
			instance = new Oval();
		}

		static public void Init() {
		}

		public static Oval Instance {
			get { return instance; }
		}

		protected Oval() : base(PowerObject.PowerObjectParent, "Oval", DrawObject.Instance) {
		}
	}
}
