// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Picture : HardwiredObject {
		static Picture instance;

		static Picture() {
			instance = new Picture();
		}

		static public void Init() {
		}

		public static Picture Instance {
			get { return instance; }
		}

		protected Picture() : base(PowerObject.PowerObjectParent, "Picture", DragObject.Instance) {
		}
	}
}
