// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class PictureListBox : HardwiredObject {
		static PictureListBox instance;

		static PictureListBox() {
			instance = new PictureListBox();
		}

		static public void Init() {
		}

		public static PictureListBox Instance {
			get { return instance; }
		}

		protected PictureListBox() : base(PowerObject.PowerObjectParent, "PictureListBox", DragObject.Instance) {
		}
	}
}
