// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class PictureHyperlink : HardwiredObject {
		static PictureHyperlink instance;

		static PictureHyperlink() {
			instance = new PictureHyperlink();
		}

		static public void Init() {
		}

		public static PictureHyperlink Instance {
			get { return instance; }
		}

		protected PictureHyperlink() : base(PowerObject.PowerObjectParent, "PictureHyperlink", Picture.Instance) {
		}
	}
}
