// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class PictureButton : HardwiredObject {
		static PictureButton instance;

		static PictureButton() {
			instance = new PictureButton();
		}

		static public void Init() {
		}

		public static PictureButton Instance {
			get { return instance; }
		}

		protected PictureButton() : base(PowerObject.PowerObjectParent, "PictureButton", CommandButton.Instance) {
		}
	}
}
