// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class RadioButton : HardwiredObject {
		static RadioButton instance;

		static RadioButton() {
			instance = new RadioButton();
		}

		static public void Init() {
		}

		public static RadioButton Instance {
			get { return instance; }
		}

		protected RadioButton() : base(PowerObject.PowerObjectParent, "RadioButton", DragObject.Instance) {
		}
	}
}
