// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Rectangle : HardwiredObject {
		static Rectangle instance;

		static Rectangle() {
			instance = new Rectangle();
		}

		static public void Init() {
		}

		public static Rectangle Instance {
			get { return instance; }
		}

		protected Rectangle() : base(PowerObject.PowerObjectParent, "Rectangle", DrawObject.Instance) {
		}
	}
}
