// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class RichTextEdit : HardwiredObject {
		static RichTextEdit instance;

		static RichTextEdit() {
			instance = new RichTextEdit();
		}

		static public void Init() {
		}

		public static RichTextEdit Instance {
			get { return instance; }
		}

		protected RichTextEdit() : base(PowerObject.PowerObjectParent, "RichTextEdit", DragObject.Instance) {
		}
	}
}
