// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class SingleLineEdit : HardwiredObject {
		static SingleLineEdit instance;

		static SingleLineEdit() {
			instance = new SingleLineEdit();
		}

		static public void Init() {
		}

		public static SingleLineEdit Instance {
			get { return instance; }
		}

		protected SingleLineEdit() : base(PowerObject.PowerObjectParent, "SingleLineEdit", DragObject.Instance) {
		}
	}
}
