// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class StaticText : HardwiredObject {
		static StaticText instance;

		static StaticText() {
			instance = new StaticText();
		}

		static public void Init() {
		}

		public static StaticText Instance {
			get { return instance; }
		}

		protected StaticText() : base(PowerObject.PowerObjectParent, "StaticText", DragObject.Instance) {
		}
	}
}
