// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Tab : HardwiredObject {
		static Tab instance;

		static Tab() {
			instance = new Tab();
		}

		static public void Init() {
		}

		public static Tab Instance {
			get { return instance; }
		}

		protected Tab() : base(PowerObject.PowerObjectParent, "Tab", DragObject.Instance) {
		}
	}
}
