// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class UserObject : HardwiredObject {
		static UserObject instance;

		static UserObject() {
			instance = new UserObject();
		}

		static public void Init() {
		}

		public static UserObject Instance {
			get { return instance; }
		}

		protected UserObject() : base(PowerObject.PowerObjectParent, "UserObject", DragObject.Instance) {
		}
	}
}
