// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class VScrollBar : HardwiredObject {
		static VScrollBar instance;

		static VScrollBar() {
			instance = new VScrollBar();
		}

		static public void Init() {
		}

		public static VScrollBar Instance {
			get { return instance; }
		}

		protected VScrollBar() : base(PowerObject.PowerObjectParent, "VScrollBar", DragObject.Instance) {
		}
	}
}
