// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class VTrackBar : HardwiredObject {
		static VTrackBar instance;

		static VTrackBar() {
			instance = new VTrackBar();
		}

		static public void Init() {
		}

		public static VTrackBar Instance {
			get { return instance; }
		}

		protected VTrackBar() : base(PowerObject.PowerObjectParent, "VTrackBar", DragObject.Instance) {
		}
	}
}
