// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Any : HardwiredObject {
		static Any instance;

		static Any() {
			instance = new Any();
		}

		static public void Init() {
		}

		public static Any Instance {
			get { return instance; }
		}

		protected Any() : base(PowerObject.PowerObjectParent, "Any", PowerObject.PowerObjectInstance) {
		}
	}
}
