// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Blob : HardwiredObject {
		static Blob instance;

		static Blob() {
			instance = new Blob();
		}

		static public void Init() {
		}

		public static Blob Instance {
			get { return instance; }
		}

		protected Blob() : base(PowerObject.PowerObjectParent, "Blob", PowerObject.PowerObjectInstance) {
		}
	}
}
