// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Boolean : HardwiredObject {
		static Boolean instance;

		static Boolean() {
			instance = new Boolean();
		}

		static public void Init() {
		}

		public static Boolean Instance {
			get { return instance; }
		}

		protected Boolean() : base(PowerObject.PowerObjectParent, "Boolean", PowerObject.PowerObjectInstance) {
		}
	}
}
