// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class DateTime : HardwiredObject {
		static DateTime instance;

		static DateTime() {
			instance = new DateTime();
		}

		static public void Init() {
		}

		public static DateTime Instance {
			get { return instance; }
		}

		protected DateTime() : base(PowerObject.PowerObjectParent, "DateTime", PowerObject.PowerObjectInstance) {
		}
	}
}
