// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Decimal : HardwiredObject {
		static Decimal instance;

		static Decimal() {
			instance = new Decimal();
		}

		static public void Init() {
		}

		public static Decimal Instance {
			get { return instance; }
		}

		protected Decimal() : base(PowerObject.PowerObjectParent, "Decimal", PowerObject.PowerObjectInstance) {
		}
	}
}
