// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Double : HardwiredObject {
		static Double instance;

		static Double() {
			instance = new Double();
		}

		static public void Init() {
		}

		public static Double Instance {
			get { return instance; }
		}

		protected Double() : base(PowerObject.PowerObjectParent, "Double", PowerObject.PowerObjectInstance) {
		}
	}
}
