// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Integer : HardwiredObject {
		static Integer instance;

		static Integer() {
			instance = new Integer();
		}

		static public void Init() {
		}

		public static Integer Instance {
			get { return instance; }
		}

		protected Integer() : base(PowerObject.PowerObjectParent, "Integer", PowerObject.PowerObjectInstance) {
			Hardwired.AddClassAlias("int", this);
		}
	}
}
