// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Long : HardwiredObject {
		static Long instance;

		static Long() {
			instance = new Long();
		}

		static public void Init() {
		}

		public static Long Instance {
			get { return instance; }
		}

		protected Long() : base(PowerObject.PowerObjectParent, "Long", PowerObject.PowerObjectInstance) {
		}
	}
}
