// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Real : HardwiredObject {
		static Real instance;

		static Real() {
			instance = new Real();
		}

		static public void Init() {
		}

		public static Real Instance {
			get { return instance; }
		}

		protected Real() : base(PowerObject.PowerObjectParent, "Real", PowerObject.PowerObjectInstance) {
		}
	}
}
