// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class String : HardwiredObject {
		static String instance;

		static String() {
			instance = new String();
		}

		static public void Init() {
		}

		public static String Instance {
			get { return instance; }
		}

		protected String() : base(PowerObject.PowerObjectParent, "String", PowerObject.PowerObjectInstance) {
		}
	}
}
