// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Time : HardwiredObject {
		static Time instance;

		static Time() {
			instance = new Time();
		}

		static public void Init() {
		}

		public static Time Instance {
			get { return instance; }
		}

		protected Time() : base(PowerObject.PowerObjectParent, "Time", PowerObject.PowerObjectInstance) {
		}
	}
}
