// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class UnsignedLong : HardwiredObject {
		static UnsignedLong instance;

		static UnsignedLong() {
			instance = new UnsignedLong();
		}

		static public void Init() {
		}

		public static UnsignedLong Instance {
			get { return instance; }
		}

		protected UnsignedLong() : base(PowerObject.PowerObjectParent, "UnsignedLong", PowerObject.PowerObjectInstance) {
		}
	}
}
