// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class UnsignedInteger : HardwiredObject {
		static UnsignedInteger instance;

		static UnsignedInteger() {
			instance = new UnsignedInteger();
		}

		static public void Init() {
		}

		public static UnsignedInteger Instance {
			get { return instance; }
		}

		protected UnsignedInteger() : base(PowerObject.PowerObjectParent, "UnsignedInteger", PowerObject.PowerObjectInstance) {
			Hardwired.AddClassAlias("unsignedint", this);
		}
	}
}
