// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class CorbaBadParam : HardwiredObject {
		static CorbaBadParam instance;

		static CorbaBadParam() {
			instance = new CorbaBadParam();
		}

		static public void Init() {
		}

		public static CorbaBadParam Instance {
			get { return instance; }
		}

		protected CorbaBadParam() : base(PowerObject.PowerObjectParent, "CorbaBadParam", CorbaSystemException.Instance) {
		}
	}
}
