// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class CorbaInvalidTransaction : HardwiredObject {
		static CorbaInvalidTransaction instance;

		static CorbaInvalidTransaction() {
			instance = new CorbaInvalidTransaction();
		}

		static public void Init() {
		}

		public static CorbaInvalidTransaction Instance {
			get { return instance; }
		}

		protected CorbaInvalidTransaction() : base(PowerObject.PowerObjectParent, "CorbaInvalidTransaction", CorbaSystemException.Instance) {
		}
	}
}
