// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class CorbaBadInvOrder : HardwiredObject {
		static CorbaBadInvOrder instance;

		static CorbaBadInvOrder() {
			instance = new CorbaBadInvOrder();
		}

		static public void Init() {
		}

		public static CorbaBadInvOrder Instance {
			get { return instance; }
		}

		protected CorbaBadInvOrder() : base(PowerObject.PowerObjectParent, "CorbaBadInvOrder", CorbaSystemException.Instance) {
		}
	}
}
