// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class CorbaBadDataConversion : HardwiredObject {
		static CorbaBadDataConversion instance;

		static CorbaBadDataConversion() {
			instance = new CorbaBadDataConversion();
		}

		static public void Init() {
		}

		public static CorbaBadDataConversion Instance {
			get { return instance; }
		}

		protected CorbaBadDataConversion() : base(PowerObject.PowerObjectParent, "CorbaBadDataConversion", CorbaSystemException.Instance) {
		}
	}
}
