// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class CorbaBadTypeCode : HardwiredObject {
		static CorbaBadTypeCode instance;

		static CorbaBadTypeCode() {
			instance = new CorbaBadTypeCode();
		}

		static public void Init() {
		}

		public static CorbaBadTypeCode Instance {
			get { return instance; }
		}

		protected CorbaBadTypeCode() : base(PowerObject.PowerObjectParent, "CorbaBadTypeCode", CorbaSystemException.Instance) {
		}
	}
}
