// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class CorbaNoPermission : HardwiredObject {
		static CorbaNoPermission instance;

		static CorbaNoPermission() {
			instance = new CorbaNoPermission();
		}

		static public void Init() {
		}

		public static CorbaNoPermission Instance {
			get { return instance; }
		}

		protected CorbaNoPermission() : base(PowerObject.PowerObjectParent, "CorbaNoPermission", CorbaSystemException.Instance) {
		}
	}
}
