// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class CorbaInvObjRef : HardwiredObject {
		static CorbaInvObjRef instance;

		static CorbaInvObjRef() {
			instance = new CorbaInvObjRef();
		}

		static public void Init() {
		}

		public static CorbaInvObjRef Instance {
			get { return instance; }
		}

		protected CorbaInvObjRef() : base(PowerObject.PowerObjectParent, "CorbaInvObjRef", CorbaSystemException.Instance) {
		}
	}
}
