// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class CorbaIntFrePos : HardwiredObject {
		static CorbaIntFrePos instance;

		static CorbaIntFrePos() {
			instance = new CorbaIntFrePos();
		}

		static public void Init() {
		}

		public static CorbaIntFrePos Instance {
			get { return instance; }
		}

		protected CorbaIntFrePos() : base(PowerObject.PowerObjectParent, "CorbaIntFrePos", CorbaSystemException.Instance) {
		}
	}
}
