// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class CorbaUnknown : HardwiredObject {
		static CorbaUnknown instance;

		static CorbaUnknown() {
			instance = new CorbaUnknown();
		}

		static public void Init() {
		}

		public static CorbaUnknown Instance {
			get { return instance; }
		}

		protected CorbaUnknown() : base(PowerObject.PowerObjectParent, "CorbaUnknown", CorbaSystemException.Instance) {
		}
	}
}
