// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class CorbaImpLimit : HardwiredObject {
		static CorbaImpLimit instance;

		static CorbaImpLimit() {
			instance = new CorbaImpLimit();
		}

		static public void Init() {
		}

		public static CorbaImpLimit Instance {
			get { return instance; }
		}

		protected CorbaImpLimit() : base(PowerObject.PowerObjectParent, "CorbaImpLimit", CorbaSystemException.Instance) {
		}
	}
}
