// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class CorbaNoMemory : HardwiredObject {
		static CorbaNoMemory instance;

		static CorbaNoMemory() {
			instance = new CorbaNoMemory();
		}

		static public void Init() {
		}

		public static CorbaNoMemory Instance {
			get { return instance; }
		}

		protected CorbaNoMemory() : base(PowerObject.PowerObjectParent, "CorbaNoMemory", CorbaSystemException.Instance) {
		}
	}
}
