// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class CorbaCurrent : HardwiredObject {
		static CorbaCurrent instance;

		static CorbaCurrent() {
			instance = new CorbaCurrent();
		}

		static public void Init() {
		}

		public static CorbaCurrent Instance {
			get { return instance; }
		}

		protected CorbaCurrent() : base(PowerObject.PowerObjectParent, "CorbaCurrent", Service.Instance) {
		}
	}
}
