// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class CorbaCommFailure : HardwiredObject {
		static CorbaCommFailure instance;

		static CorbaCommFailure() {
			instance = new CorbaCommFailure();
		}

		static public void Init() {
		}

		public static CorbaCommFailure Instance {
			get { return instance; }
		}

		protected CorbaCommFailure() : base(PowerObject.PowerObjectParent, "CorbaCommFailure", CorbaSystemException.Instance) {
		}
	}
}
