// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class CorbaNoResources : HardwiredObject {
		static CorbaNoResources instance;

		static CorbaNoResources() {
			instance = new CorbaNoResources();
		}

		static public void Init() {
		}

		public static CorbaNoResources Instance {
			get { return instance; }
		}

		protected CorbaNoResources() : base(PowerObject.PowerObjectParent, "CorbaNoResources", CorbaSystemException.Instance) {
		}
	}
}
