// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class CorbaBadOperation : HardwiredObject {
		static CorbaBadOperation instance;

		static CorbaBadOperation() {
			instance = new CorbaBadOperation();
		}

		static public void Init() {
		}

		public static CorbaBadOperation Instance {
			get { return instance; }
		}

		protected CorbaBadOperation() : base(PowerObject.PowerObjectParent, "CorbaBadOperation", CorbaSystemException.Instance) {
		}
	}
}
