// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class CorbaSystemException : HardwiredObject {
		static CorbaSystemException instance;

		static CorbaSystemException() {
			instance = new CorbaSystemException();
		}

		static public void Init() {
		}

		public static CorbaSystemException Instance {
			get { return instance; }
		}

		protected CorbaSystemException() : base(PowerObject.PowerObjectParent, "CorbaSystemException", RuntimeError.Instance) {
		}
	}
}
