// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class CorbaFreeMem : HardwiredObject {
		static CorbaFreeMem instance;

		static CorbaFreeMem() {
			instance = new CorbaFreeMem();
		}

		static public void Init() {
		}

		public static CorbaFreeMem Instance {
			get { return instance; }
		}

		protected CorbaFreeMem() : base(PowerObject.PowerObjectParent, "CorbaFreeMem", CorbaSystemException.Instance) {
		}
	}
}
