// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class CorbaBadAdContext : HardwiredObject {
		static CorbaBadAdContext instance;

		static CorbaBadAdContext() {
			instance = new CorbaBadAdContext();
		}

		static public void Init() {
		}

		public static CorbaBadAdContext Instance {
			get { return instance; }
		}

		protected CorbaBadAdContext() : base(PowerObject.PowerObjectParent, "CorbaBadAdContext", CorbaSystemException.Instance) {
		}
	}
}
