// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class CorbaTransactionRolledBack : HardwiredObject {
		static CorbaTransactionRolledBack instance;

		static CorbaTransactionRolledBack() {
			instance = new CorbaTransactionRolledBack();
		}

		static public void Init() {
		}

		public static CorbaTransactionRolledBack Instance {
			get { return instance; }
		}

		protected CorbaTransactionRolledBack() : base(PowerObject.PowerObjectParent, "CorbaTransactionRolledBack", CorbaSystemException.Instance) {
		}
	}
}
