// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class CorbaObjectNotExists : HardwiredObject {
		static CorbaObjectNotExists instance;

		static CorbaObjectNotExists() {
			instance = new CorbaObjectNotExists();
		}

		static public void Init() {
		}

		public static CorbaObjectNotExists Instance {
			get { return instance; }
		}

		protected CorbaObjectNotExists() : base(PowerObject.PowerObjectParent, "CorbaObjectNotExists", CorbaSystemException.Instance) {
		}
	}
}
