// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class CorbaInternal : HardwiredObject {
		static CorbaInternal instance;

		static CorbaInternal() {
			instance = new CorbaInternal();
		}

		static public void Init() {
		}

		public static CorbaInternal Instance {
			get { return instance; }
		}

		protected CorbaInternal() : base(PowerObject.PowerObjectParent, "CorbaInternal", CorbaSystemException.Instance) {
		}
	}
}
