// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class CorbaUserException : HardwiredObject {
		static CorbaUserException instance;

		static CorbaUserException() {
			instance = new CorbaUserException();
		}

		static public void Init() {
		}

		public static CorbaUserException Instance {
			get { return instance; }
		}

		protected CorbaUserException() : base(PowerObject.PowerObjectParent, "CorbaUserException", Exception.Instance) {
		}
	}
}
