// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class CorbaObjAdapter : HardwiredObject {
		static CorbaObjAdapter instance;

		static CorbaObjAdapter() {
			instance = new CorbaObjAdapter();
		}

		static public void Init() {
		}

		public static CorbaObjAdapter Instance {
			get { return instance; }
		}

		protected CorbaObjAdapter() : base(PowerObject.PowerObjectParent, "CorbaObjAdapter", CorbaSystemException.Instance) {
		}
	}
}
