// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class CorbaNoImplement : HardwiredObject {
		static CorbaNoImplement instance;

		static CorbaNoImplement() {
			instance = new CorbaNoImplement();
		}

		static public void Init() {
		}

		public static CorbaNoImplement Instance {
			get { return instance; }
		}

		protected CorbaNoImplement() : base(PowerObject.PowerObjectParent, "CorbaNoImplement", CorbaSystemException.Instance) {
		}
	}
}
