// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class CorbaInvIdent : HardwiredObject {
		static CorbaInvIdent instance;

		static CorbaInvIdent() {
			instance = new CorbaInvIdent();
		}

		static public void Init() {
		}

		public static CorbaInvIdent Instance {
			get { return instance; }
		}

		protected CorbaInvIdent() : base(PowerObject.PowerObjectParent, "CorbaInvIdent", CorbaSystemException.Instance) {
		}
	}
}
