// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class CorbaMarshal : HardwiredObject {
		static CorbaMarshal instance;

		static CorbaMarshal() {
			instance = new CorbaMarshal();
		}

		static public void Init() {
		}

		public static CorbaMarshal Instance {
			get { return instance; }
		}

		protected CorbaMarshal() : base(PowerObject.PowerObjectParent, "CorbaMarshal", CorbaSystemException.Instance) {
		}
	}
}
