// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class CorbaTransient : HardwiredObject {
		static CorbaTransient instance;

		static CorbaTransient() {
			instance = new CorbaTransient();
		}

		static public void Init() {
		}

		public static CorbaTransient Instance {
			get { return instance; }
		}

		protected CorbaTransient() : base(PowerObject.PowerObjectParent, "CorbaTransient", CorbaSystemException.Instance) {
		}
	}
}
