// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class DWRuntimeError : HardwiredObject {
		static DWRuntimeError instance;

		static DWRuntimeError() {
			instance = new DWRuntimeError();
		}

		static public void Init() {
		}

		public static DWRuntimeError Instance {
			get { return instance; }
		}

		protected DWRuntimeError() : base(PowerObject.PowerObjectParent, "DWRuntimeError", RuntimeError.Instance) {
		}
	}
}
