// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Exception : HardwiredObject {
		static Exception instance;

		static Exception() {
			instance = new Exception();
		}

		static public void Init() {
		}

		public static Exception Instance {
			get { return instance; }
		}

		protected Exception() : base(PowerObject.PowerObjectParent, "Exception", Throwable.Instance) {
		}
	}
}
