// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class NullObjectError : HardwiredObject {
		static NullObjectError instance;

		static NullObjectError() {
			instance = new NullObjectError();
		}

		static public void Init() {
		}

		public static NullObjectError Instance {
			get { return instance; }
		}

		protected NullObjectError() : base(PowerObject.PowerObjectParent, "NullObjectError", RuntimeError.Instance) {
		}
	}
}
