// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class OleRuntimeError : HardwiredObject {
		static OleRuntimeError instance;

		static OleRuntimeError() {
			instance = new OleRuntimeError();
		}

		static public void Init() {
		}

		public static OleRuntimeError Instance {
			get { return instance; }
		}

		protected OleRuntimeError() : base(PowerObject.PowerObjectParent, "OleRuntimeError", RuntimeError.Instance) {
		}
	}
}
