// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Throwable : HardwiredObject {
		static Throwable instance;

		static Throwable() {
			instance = new Throwable();
		}

		static public void Init() {
		}

		public static Throwable Instance {
			get { return instance; }
		}

		protected Throwable() : base(PowerObject.PowerObjectParent, "Throwable", NonVisualObject.Instance) {
		}
	}
}
