// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class ArrayBounds : HardwiredObject {
		static ArrayBounds instance;

		static ArrayBounds() {
			instance = new ArrayBounds();
		}

		static public void Init() {
		}

		public static ArrayBounds Instance {
			get { return instance; }
		}

		protected ArrayBounds() : base(PowerObject.PowerObjectParent, "ArrayBounds", ClassDefinitionObject.Instance) {
		}
	}
}
