// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class ClassDefinitionObject : HardwiredObject {
		static ClassDefinitionObject instance;

		static ClassDefinitionObject() {
			instance = new ClassDefinitionObject();
		}

		static public void Init() {
		}

		public static ClassDefinitionObject Instance {
			get { return instance; }
		}

		protected ClassDefinitionObject() : base(PowerObject.PowerObjectParent, "ClassDefinitionObject", PbToCPPObject.Instance) {
		}
	}
}
