// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class ClassDefinition : HardwiredObject {
		static ClassDefinition instance;

		static ClassDefinition() {
			instance = new ClassDefinition();
		}

		static public void Init() {
		}

		public static ClassDefinition Instance {
			get { return instance; }
		}

		protected ClassDefinition() : base(PowerObject.PowerObjectParent, "ClassDefinition", TypeDefinition.Instance) {
		}
	}
}
