// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class EnumerationDefinition : HardwiredObject {
		static EnumerationDefinition instance;

		static EnumerationDefinition() {
			instance = new EnumerationDefinition();
		}

		static public void Init() {
		}

		public static EnumerationDefinition Instance {
			get { return instance; }
		}

		protected EnumerationDefinition() : base(PowerObject.PowerObjectParent, "EnumerationDefinition", TypeDefinition.Instance) {
		}
	}
}
