// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class EnumerationItemDefinition : HardwiredObject {
		static EnumerationItemDefinition instance;

		static EnumerationItemDefinition() {
			instance = new EnumerationItemDefinition();
		}

		static public void Init() {
		}

		public static EnumerationItemDefinition Instance {
			get { return instance; }
		}

		protected EnumerationItemDefinition() : base(PowerObject.PowerObjectParent, "EnumerationItemDefinition", ClassDefinitionObject.Instance) {
		}
	}
}
