// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Profiling : HardwiredObject {
		static Profiling instance;

		static Profiling() {
			instance = new Profiling();
		}

		static public void Init() {
		}

		public static Profiling Instance {
			get { return instance; }
		}

		protected Profiling() : base(PowerObject.PowerObjectParent, "Profiling", PbToCPPObject.Instance) {
		}
	}
}
