// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class ProfileCall : HardwiredObject {
		static ProfileCall instance;

		static ProfileCall() {
			instance = new ProfileCall();
		}

		static public void Init() {
		}

		public static ProfileCall Instance {
			get { return instance; }
		}

		protected ProfileCall() : base(PowerObject.PowerObjectParent, "ProfileCall", PbToCPPObject.Instance) {
		}
	}
}
