// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class ProfileClass : HardwiredObject {
		static ProfileClass instance;

		static ProfileClass() {
			instance = new ProfileClass();
		}

		static public void Init() {
		}

		public static ProfileClass Instance {
			get { return instance; }
		}

		protected ProfileClass() : base(PowerObject.PowerObjectParent, "ProfileClass", PbToCPPObject.Instance) {
		}
	}
}
