// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class SimpleTypeDefinition : HardwiredObject {
		static SimpleTypeDefinition instance;

		static SimpleTypeDefinition() {
			instance = new SimpleTypeDefinition();
		}

		static public void Init() {
		}

		public static SimpleTypeDefinition Instance {
			get { return instance; }
		}

		protected SimpleTypeDefinition() : base(PowerObject.PowerObjectParent, "SimpleTypeDefinition", TypeDefinition.Instance) {
		}
	}
}
