// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class TraceTreeNode : HardwiredObject {
		static TraceTreeNode instance;

		static TraceTreeNode() {
			instance = new TraceTreeNode();
		}

		static public void Init() {
		}

		public static TraceTreeNode Instance {
			get { return instance; }
		}

		protected TraceTreeNode() : base(PowerObject.PowerObjectParent, "TraceTreeNode", PbToCPPObject.Instance) {
		}
	}
}
