// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class TraceTreeError : HardwiredObject {
		static TraceTreeError instance;

		static TraceTreeError() {
			instance = new TraceTreeError();
		}

		static public void Init() {
		}

		public static TraceTreeError Instance {
			get { return instance; }
		}

		protected TraceTreeError() : base(PowerObject.PowerObjectParent, "TraceTreeError", TraceTreeNode.Instance) {
		}
	}
}
