// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class TraceTreeLine : HardwiredObject {
		static TraceTreeLine instance;

		static TraceTreeLine() {
			instance = new TraceTreeLine();
		}

		static public void Init() {
		}

		public static TraceTreeLine Instance {
			get { return instance; }
		}

		protected TraceTreeLine() : base(PowerObject.PowerObjectParent, "TraceTreeLine", TraceTreeNode.Instance) {
		}
	}
}
