// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class TraceTree : HardwiredObject {
		static TraceTree instance;

		static TraceTree() {
			instance = new TraceTree();
		}

		static public void Init() {
		}

		public static TraceTree Instance {
			get { return instance; }
		}

		protected TraceTree() : base(PowerObject.PowerObjectParent, "TraceTree", PbToCPPObject.Instance) {
		}
	}
}
