// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class TraceTreeSQL : HardwiredObject {
		static TraceTreeSQL instance;

		static TraceTreeSQL() {
			instance = new TraceTreeSQL();
		}

		static public void Init() {
		}

		public static TraceTreeSQL Instance {
			get { return instance; }
		}

		protected TraceTreeSQL() : base(PowerObject.PowerObjectParent, "TraceTreeSQL", TraceTreeNode.Instance) {
		}
	}
}
