// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class TraceTreeObject : HardwiredObject {
		static TraceTreeObject instance;

		static TraceTreeObject() {
			instance = new TraceTreeObject();
		}

		static public void Init() {
		}

		public static TraceTreeObject Instance {
			get { return instance; }
		}

		protected TraceTreeObject() : base(PowerObject.PowerObjectParent, "TraceTreeObject", TraceTreeNode.Instance) {
		}
	}
}
