// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class TraceTreeGarbageCollect : HardwiredObject {
		static TraceTreeGarbageCollect instance;

		static TraceTreeGarbageCollect() {
			instance = new TraceTreeGarbageCollect();
		}

		static public void Init() {
		}

		public static TraceTreeGarbageCollect Instance {
			get { return instance; }
		}

		protected TraceTreeGarbageCollect() : base(PowerObject.PowerObjectParent, "TraceTreeGarbageCollect", TraceTreeNode.Instance) {
		}
	}
}
