// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class TypeDefinition : HardwiredObject {
		static TypeDefinition instance;

		static TypeDefinition() {
			instance = new TypeDefinition();
		}

		static public void Init() {
		}

		public static TypeDefinition Instance {
			get { return instance; }
		}

		protected TypeDefinition() : base(PowerObject.PowerObjectParent, "TypeDefinition", ClassDefinitionObject.Instance) {
		}
	}
}
