// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class VariableDefinition : HardwiredObject {
		static VariableDefinition instance;

		static VariableDefinition() {
			instance = new VariableDefinition();
		}

		static public void Init() {
		}

		public static VariableDefinition Instance {
			get { return instance; }
		}

		protected VariableDefinition() : base(PowerObject.PowerObjectParent, "VariableDefinition", ClassDefinitionObject.Instance) {
		}
	}
}
