// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class VariableCardinalityDefinition : HardwiredObject {
		static VariableCardinalityDefinition instance;

		static VariableCardinalityDefinition() {
			instance = new VariableCardinalityDefinition();
		}

		static public void Init() {
		}

		public static VariableCardinalityDefinition Instance {
			get { return instance; }
		}

		protected VariableCardinalityDefinition() : base(PowerObject.PowerObjectParent, "VariableCardinalityDefinition", ClassDefinitionObject.Instance) {
		}
	}
}
