// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class function_object : HardwiredObject {
		static function_object instance;

		static function_object() {
			instance = new function_object();
		}

		static public void Init() {
		}

		public static function_object Instance {
			get { return instance; }
		}

		protected function_object() : base(PowerObject.PowerObjectParent, "function_object", PowerObject.PowerObjectInstance) {
		}
	}
}
