// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class GrAxis : HardwiredObject {
		static GrAxis instance;

		static GrAxis() {
			instance = new GrAxis();
		}

		static public void Init() {
		}

		public static GrAxis Instance {
			get { return instance; }
		}

		protected GrAxis() : base(PowerObject.PowerObjectParent, "GrAxis", PowerObject.PowerObjectInstance) {
		}
	}
}
