// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class GrDispAttr : HardwiredObject {
		static GrDispAttr instance;

		static GrDispAttr() {
			instance = new GrDispAttr();
		}

		static public void Init() {
		}

		public static GrDispAttr Instance {
			get { return instance; }
		}

		protected GrDispAttr() : base(PowerObject.PowerObjectParent, "GrDispAttr", PowerObject.PowerObjectInstance) {
		}
	}
}
