// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class ArrangeTypes : HardwiredObject {
		static ArrangeTypes instance;

		static ArrangeTypes() {
			instance = new ArrangeTypes();
		}

		static public void Init() {
		}

		public static ArrangeTypes Instance {
			get { return instance; }
		}

		protected ArrangeTypes() : base(PowerObject.PowerObjectParent, "ArrangeTypes", EnumeratedType.Instance) {
		}
	}
}
