// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class ArrangeOpen : HardwiredObject {
		static ArrangeOpen instance;

		static ArrangeOpen() {
			instance = new ArrangeOpen();
		}

		static public void Init() {
		}

		public static ArrangeOpen Instance {
			get { return instance; }
		}

		protected ArrangeOpen() : base(PowerObject.PowerObjectParent, "ArrangeOpen", EnumeratedType.Instance) {
		}
	}
}
