// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Band : HardwiredObject {
		static Band instance;

		static Band() {
			instance = new Band();
		}

		static public void Init() {
		}

		public static Band Instance {
			get { return instance; }
		}

		protected Band() : base(PowerObject.PowerObjectParent, "Band", EnumeratedType.Instance) {
		}
	}
}
