// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Border : HardwiredObject {
		static Border instance;

		static Border() {
			instance = new Border();
		}

		static public void Init() {
		}

		public static Border Instance {
			get { return instance; }
		}

		protected Border() : base(PowerObject.PowerObjectParent, "Border", EnumeratedType.Instance) {
		}
	}
}
