// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class BorderStyle : HardwiredObject {
		static BorderStyle instance;

		static BorderStyle() {
			instance = new BorderStyle();
		}

		static public void Init() {
		}

		public static BorderStyle Instance {
			get { return instance; }
		}

		protected BorderStyle() : base(PowerObject.PowerObjectParent, "BorderStyle", EnumeratedType.Instance) {
		}
	}
}
