// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class CharSet : HardwiredObject {
		static CharSet instance;

		static CharSet() {
			instance = new CharSet();
		}

		static public void Init() {
		}

		public static CharSet Instance {
			get { return instance; }
		}

		protected CharSet() : base(PowerObject.PowerObjectParent, "CharSet", EnumeratedType.Instance) {
		}
	}
}
