// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class ClipboardFormat : HardwiredObject {
		static ClipboardFormat instance;

		static ClipboardFormat() {
			instance = new ClipboardFormat();
		}

		static public void Init() {
		}

		public static ClipboardFormat Instance {
			get { return instance; }
		}

		protected ClipboardFormat() : base(PowerObject.PowerObjectParent, "ClipboardFormat", EnumeratedType.Instance) {
		}
	}
}
