// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class ConvertType : HardwiredObject {
		static ConvertType instance;

		static ConvertType() {
			instance = new ConvertType();
		}

		static public void Init() {
		}

		public static ConvertType Instance {
			get { return instance; }
		}

		protected ConvertType() : base(PowerObject.PowerObjectParent, "ConvertType", EnumeratedType.Instance) {
		}
	}
}
