// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class DateTimeFormat : HardwiredObject {
		static DateTimeFormat instance;

		static DateTimeFormat() {
			instance = new DateTimeFormat();
		}

		static public void Init() {
		}

		public static DateTimeFormat Instance {
			get { return instance; }
		}

		protected DateTimeFormat() : base(PowerObject.PowerObjectParent, "DateTimeFormat", EnumeratedType.Instance) {
		}
	}
}
