// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Direction : HardwiredObject {
		static Direction instance;

		static Direction() {
			instance = new Direction();
		}

		static public void Init() {
		}

		public static Direction Instance {
			get { return instance; }
		}

		protected Direction() : base(PowerObject.PowerObjectParent, "Direction", EnumeratedType.Instance) {
		}
	}
}
