// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class DisplaySizeMode : HardwiredObject {
		static DisplaySizeMode instance;

		static DisplaySizeMode() {
			instance = new DisplaySizeMode();
		}

		static public void Init() {
		}

		public static DisplaySizeMode Instance {
			get { return instance; }
		}

		protected DisplaySizeMode() : base(PowerObject.PowerObjectParent, "DisplaySizeMode", EnumeratedType.Instance) {
		}
	}
}
