// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class DragModes : HardwiredObject {
		static DragModes instance;

		static DragModes() {
			instance = new DragModes();
		}

		static public void Init() {
		}

		public static DragModes Instance {
			get { return instance; }
		}

		protected DragModes() : base(PowerObject.PowerObjectParent, "DragModes", EnumeratedType.Instance) {
		}
	}
}
