// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class DWBuffer : HardwiredObject {
		static DWBuffer instance;

		static DWBuffer() {
			instance = new DWBuffer();
		}

		static public void Init() {
		}

		public static DWBuffer Instance {
			get { return instance; }
		}

		protected DWBuffer() : base(PowerObject.PowerObjectParent, "DWBuffer", EnumeratedType.Instance) {
		}
	}
}
