// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class DWConflictResolution : HardwiredObject {
		static DWConflictResolution instance;

		static DWConflictResolution() {
			instance = new DWConflictResolution();
		}

		static public void Init() {
		}

		public static DWConflictResolution Instance {
			get { return instance; }
		}

		protected DWConflictResolution() : base(PowerObject.PowerObjectParent, "DWConflictResolution", EnumeratedType.Instance) {
		}
	}
}
