// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class DWItemStatus : HardwiredObject {
		static DWItemStatus instance;

		static DWItemStatus() {
			instance = new DWItemStatus();
		}

		static public void Init() {
		}

		public static DWItemStatus Instance {
			get { return instance; }
		}

		protected DWItemStatus() : base(PowerObject.PowerObjectParent, "DWItemStatus", EnumeratedType.Instance) {
		}
	}
}
