// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class EnumeratedType : HardwiredObject {
		static EnumeratedType instance;

		static EnumeratedType() {
			instance = new EnumeratedType();
		}

		static public void Init() {
		}

		public static EnumeratedType Instance {
			get { return instance; }
		}

		protected EnumeratedType() : base(PowerObject.PowerObjectParent, "EnumeratedType", PowerObject.PowerObjectInstance) {
		}
	}
}
