// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class ErrorReturn : HardwiredObject {
		static ErrorReturn instance;

		static ErrorReturn() {
			instance = new ErrorReturn();
		}

		static public void Init() {
		}

		public static ErrorReturn Instance {
			get { return instance; }
		}

		protected ErrorReturn() : base(PowerObject.PowerObjectParent, "ErrorReturn", EnumeratedType.Instance) {
		}
	}
}
