// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class ExceptionAction : HardwiredObject {
		static ExceptionAction instance;

		static ExceptionAction() {
			instance = new ExceptionAction();
		}

		static public void Init() {
		}

		public static ExceptionAction Instance {
			get { return instance; }
		}

		protected ExceptionAction() : base(PowerObject.PowerObjectParent, "ExceptionAction", EnumeratedType.Instance) {
		}
	}
}
