// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class FileAccess : HardwiredObject {
		static FileAccess instance;

		static FileAccess() {
			instance = new FileAccess();
		}

		static public void Init() {
		}

		public static FileAccess Instance {
			get { return instance; }
		}

		protected FileAccess() : base(PowerObject.PowerObjectParent, "FileAccess", EnumeratedType.Instance) {
		}
	}
}
