// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class FileLock : HardwiredObject {
		static FileLock instance;

		static FileLock() {
			instance = new FileLock();
		}

		static public void Init() {
		}

		public static FileLock Instance {
			get { return instance; }
		}

		protected FileLock() : base(PowerObject.PowerObjectParent, "FileLock", EnumeratedType.Instance) {
		}
	}
}
