// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class FileMode : HardwiredObject {
		static FileMode instance;

		static FileMode() {
			instance = new FileMode();
		}

		static public void Init() {
		}

		public static FileMode Instance {
			get { return instance; }
		}

		protected FileMode() : base(PowerObject.PowerObjectParent, "FileMode", EnumeratedType.Instance) {
		}
	}
}
