// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class FileType : HardwiredObject {
		static FileType instance;

		static FileType() {
			instance = new FileType();
		}

		static public void Init() {
		}

		public static FileType Instance {
			get { return instance; }
		}

		protected FileType() : base(PowerObject.PowerObjectParent, "FileType", EnumeratedType.Instance) {
		}
	}
}
