// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class FillPattern : HardwiredObject {
		static FillPattern instance;

		static FillPattern() {
			instance = new FillPattern();
		}

		static public void Init() {
		}

		public static FillPattern Instance {
			get { return instance; }
		}

		protected FillPattern() : base(PowerObject.PowerObjectParent, "FillPattern", EnumeratedType.Instance) {
		}
	}
}
