// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class FontPitch : HardwiredObject {
		static FontPitch instance;

		static FontPitch() {
			instance = new FontPitch();
		}

		static public void Init() {
		}

		public static FontPitch Instance {
			get { return instance; }
		}

		protected FontPitch() : base(PowerObject.PowerObjectParent, "FontPitch", EnumeratedType.Instance) {
		}
	}
}
