// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class FontCharSet : HardwiredObject {
		static FontCharSet instance;

		static FontCharSet() {
			instance = new FontCharSet();
		}

		static public void Init() {
		}

		public static FontCharSet Instance {
			get { return instance; }
		}

		protected FontCharSet() : base(PowerObject.PowerObjectParent, "FontCharSet", EnumeratedType.Instance) {
		}
	}
}
