// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class GrColorType : HardwiredObject {
		static GrColorType instance;

		static GrColorType() {
			instance = new GrColorType();
		}

		static public void Init() {
		}

		public static GrColorType Instance {
			get { return instance; }
		}

		protected GrColorType() : base(PowerObject.PowerObjectParent, "GrColorType", EnumeratedType.Instance) {
		}
	}
}
