// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class GrGraphType : HardwiredObject {
		static GrGraphType instance;

		static GrGraphType() {
			instance = new GrGraphType();
		}

		static public void Init() {
		}

		public static GrGraphType Instance {
			get { return instance; }
		}

		protected GrGraphType() : base(PowerObject.PowerObjectParent, "GrGraphType", EnumeratedType.Instance) {
		}
	}
}
