// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class GrLegendType : HardwiredObject {
		static GrLegendType instance;

		static GrLegendType() {
			instance = new GrLegendType();
		}

		static public void Init() {
		}

		public static GrLegendType Instance {
			get { return instance; }
		}

		protected GrLegendType() : base(PowerObject.PowerObjectParent, "GrLegendType", EnumeratedType.Instance) {
		}
	}
}
