// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class GrObjectType : HardwiredObject {
		static GrObjectType instance;

		static GrObjectType() {
			instance = new GrObjectType();
		}

		static public void Init() {
		}

		public static GrObjectType Instance {
			get { return instance; }
		}

		protected GrObjectType() : base(PowerObject.PowerObjectParent, "GrObjectType", EnumeratedType.Instance) {
		}
	}
}
