// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class GrResetType : HardwiredObject {
		static GrResetType instance;

		static GrResetType() {
			instance = new GrResetType();
		}

		static public void Init() {
		}

		public static GrResetType Instance {
			get { return instance; }
		}

		protected GrResetType() : base(PowerObject.PowerObjectParent, "GrResetType", EnumeratedType.Instance) {
		}
	}
}
