// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class GrScaleValue : HardwiredObject {
		static GrScaleValue instance;

		static GrScaleValue() {
			instance = new GrScaleValue();
		}

		static public void Init() {
		}

		public static GrScaleValue Instance {
			get { return instance; }
		}

		protected GrScaleValue() : base(PowerObject.PowerObjectParent, "GrScaleValue", EnumeratedType.Instance) {
		}
	}
}
