// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class GrSortType : HardwiredObject {
		static GrSortType instance;

		static GrSortType() {
			instance = new GrSortType();
		}

		static public void Init() {
		}

		public static GrSortType Instance {
			get { return instance; }
		}

		protected GrSortType() : base(PowerObject.PowerObjectParent, "GrSortType", EnumeratedType.Instance) {
		}
	}
}
