// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class GrSymbolType : HardwiredObject {
		static GrSymbolType instance;

		static GrSymbolType() {
			instance = new GrSymbolType();
		}

		static public void Init() {
		}

		public static GrSymbolType Instance {
			get { return instance; }
		}

		protected GrSymbolType() : base(PowerObject.PowerObjectParent, "GrSymbolType", EnumeratedType.Instance) {
		}
	}
}
