// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class GrTicType : HardwiredObject {
		static GrTicType instance;

		static GrTicType() {
			instance = new GrTicType();
		}

		static public void Init() {
		}

		public static GrTicType Instance {
			get { return instance; }
		}

		protected GrTicType() : base(PowerObject.PowerObjectParent, "GrTicType", EnumeratedType.Instance) {
		}
	}
}
