// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class HelpCommand : HardwiredObject {
		static HelpCommand instance;

		static HelpCommand() {
			instance = new HelpCommand();
		}

		static public void Init() {
		}

		public static HelpCommand Instance {
			get { return instance; }
		}

		protected HelpCommand() : base(PowerObject.PowerObjectParent, "HelpCommand", EnumeratedType.Instance) {
		}
	}
}
