// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class HTickMarks : HardwiredObject {
		static HTickMarks instance;

		static HTickMarks() {
			instance = new HTickMarks();
		}

		static public void Init() {
		}

		public static HTickMarks Instance {
			get { return instance; }
		}

		protected HTickMarks() : base(PowerObject.PowerObjectParent, "HTickMarks", EnumeratedType.Instance) {
		}
	}
}
