// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Icon : HardwiredObject {
		static Icon instance;

		static Icon() {
			instance = new Icon();
		}

		static public void Init() {
		}

		public static Icon Instance {
			get { return instance; }
		}

		protected Icon() : base(PowerObject.PowerObjectParent, "Icon", EnumeratedType.Instance) {
		}
	}
}
