// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class InkCollectionMode : HardwiredObject {
		static InkCollectionMode instance;

		static InkCollectionMode() {
			instance = new InkCollectionMode();
		}

		static public void Init() {
		}

		public static InkCollectionMode Instance {
			get { return instance; }
		}

		protected InkCollectionMode() : base(PowerObject.PowerObjectParent, "InkCollectionMode", EnumeratedType.Instance) {
		}
	}
}
