// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class InkCompressionMode : HardwiredObject {
		static InkCompressionMode instance;

		static InkCompressionMode() {
			instance = new InkCompressionMode();
		}

		static public void Init() {
		}

		public static InkCompressionMode Instance {
			get { return instance; }
		}

		protected InkCompressionMode() : base(PowerObject.PowerObjectParent, "InkCompressionMode", EnumeratedType.Instance) {
		}
	}
}
