// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class InkEditStatus : HardwiredObject {
		static InkEditStatus instance;

		static InkEditStatus() {
			instance = new InkEditStatus();
		}

		static public void Init() {
		}

		public static InkEditStatus Instance {
			get { return instance; }
		}

		protected InkEditStatus() : base(PowerObject.PowerObjectParent, "InkEditStatus", EnumeratedType.Instance) {
		}
	}
}
