// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class InkPicEditMode : HardwiredObject {
		static InkPicEditMode instance;

		static InkPicEditMode() {
			instance = new InkPicEditMode();
		}

		static public void Init() {
		}

		public static InkPicEditMode Instance {
			get { return instance; }
		}

		protected InkPicEditMode() : base(PowerObject.PowerObjectParent, "InkPicEditMode", EnumeratedType.Instance) {
		}
	}
}
