// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class InkPersistenceFormat : HardwiredObject {
		static InkPersistenceFormat instance;

		static InkPersistenceFormat() {
			instance = new InkPersistenceFormat();
		}

		static public void Init() {
		}

		public static InkPersistenceFormat Instance {
			get { return instance; }
		}

		protected InkPersistenceFormat() : base(PowerObject.PowerObjectParent, "InkPersistenceFormat", EnumeratedType.Instance) {
		}
	}
}
