// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class KeyCode : HardwiredObject {
		static KeyCode instance;

		static KeyCode() {
			instance = new KeyCode();
		}

		static public void Init() {
		}

		public static KeyCode Instance {
			get { return instance; }
		}

		protected KeyCode() : base(PowerObject.PowerObjectParent, "KeyCode", EnumeratedType.Instance) {
		}
	}
}
