// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class LanguageID : HardwiredObject {
		static LanguageID instance;

		static LanguageID() {
			instance = new LanguageID();
		}

		static public void Init() {
		}

		public static LanguageID Instance {
			get { return instance; }
		}

		protected LanguageID() : base(PowerObject.PowerObjectParent, "LanguageID", EnumeratedType.Instance) {
		}
	}
}
