// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class LanguageSortID : HardwiredObject {
		static LanguageSortID instance;

		static LanguageSortID() {
			instance = new LanguageSortID();
		}

		static public void Init() {
		}

		public static LanguageSortID Instance {
			get { return instance; }
		}

		protected LanguageSortID() : base(PowerObject.PowerObjectParent, "LanguageSortID", EnumeratedType.Instance) {
		}
	}
}
