// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class LibDirType : HardwiredObject {
		static LibDirType instance;

		static LibDirType() {
			instance = new LibDirType();
		}

		static public void Init() {
		}

		public static LibDirType Instance {
			get { return instance; }
		}

		protected LibDirType() : base(PowerObject.PowerObjectParent, "LibDirType", EnumeratedType.Instance) {
		}
	}
}
