// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class LibImportType : HardwiredObject {
		static LibImportType instance;

		static LibImportType() {
			instance = new LibImportType();
		}

		static public void Init() {
		}

		public static LibImportType Instance {
			get { return instance; }
		}

		protected LibImportType() : base(PowerObject.PowerObjectParent, "LibImportType", EnumeratedType.Instance) {
		}
	}
}
