// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class LineStyle : HardwiredObject {
		static LineStyle instance;

		static LineStyle() {
			instance = new LineStyle();
		}

		static public void Init() {
		}

		public static LineStyle Instance {
			get { return instance; }
		}

		protected LineStyle() : base(PowerObject.PowerObjectParent, "LineStyle", EnumeratedType.Instance) {
		}
	}
}
