// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class ListViewView : HardwiredObject {
		static ListViewView instance;

		static ListViewView() {
			instance = new ListViewView();
		}

		static public void Init() {
		}

		public static ListViewView Instance {
			get { return instance; }
		}

		protected ListViewView() : base(PowerObject.PowerObjectParent, "ListViewView", EnumeratedType.Instance) {
		}
	}
}
