// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Location : HardwiredObject {
		static Location instance;

		static Location() {
			instance = new Location();
		}

		static public void Init() {
		}

		public static Location Instance {
			get { return instance; }
		}

		protected Location() : base(PowerObject.PowerObjectParent, "Location", EnumeratedType.Instance) {
		}
	}
}
