// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class MailFileType : HardwiredObject {
		static MailFileType instance;

		static MailFileType() {
			instance = new MailFileType();
		}

		static public void Init() {
		}

		public static MailFileType Instance {
			get { return instance; }
		}

		protected MailFileType() : base(PowerObject.PowerObjectParent, "MailFileType", EnumeratedType.Instance) {
		}
	}
}
