// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class MailRecipientType : HardwiredObject {
		static MailRecipientType instance;

		static MailRecipientType() {
			instance = new MailRecipientType();
		}

		static public void Init() {
		}

		public static MailRecipientType Instance {
			get { return instance; }
		}

		protected MailRecipientType() : base(PowerObject.PowerObjectParent, "MailRecipientType", EnumeratedType.Instance) {
		}
	}
}
