// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class MailReadOption : HardwiredObject {
		static MailReadOption instance;

		static MailReadOption() {
			instance = new MailReadOption();
		}

		static public void Init() {
		}

		public static MailReadOption Instance {
			get { return instance; }
		}

		protected MailReadOption() : base(PowerObject.PowerObjectParent, "MailReadOption", EnumeratedType.Instance) {
		}
	}
}
