// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class MailReturnCode : HardwiredObject {
		static MailReturnCode instance;

		static MailReturnCode() {
			instance = new MailReturnCode();
		}

		static public void Init() {
		}

		public static MailReturnCode Instance {
			get { return instance; }
		}

		protected MailReturnCode() : base(PowerObject.PowerObjectParent, "MailReturnCode", EnumeratedType.Instance) {
		}
	}
}
