// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class MenuMergeOption : HardwiredObject {
		static MenuMergeOption instance;

		static MenuMergeOption() {
			instance = new MenuMergeOption();
		}

		static public void Init() {
		}

		public static MenuMergeOption Instance {
			get { return instance; }
		}

		protected MenuMergeOption() : base(PowerObject.PowerObjectParent, "MenuMergeOption", EnumeratedType.Instance) {
		}
	}
}
