// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class MenuStyle : HardwiredObject {
		static MenuStyle instance;

		static MenuStyle() {
			instance = new MenuStyle();
		}

		static public void Init() {
		}

		public static MenuStyle Instance {
			get { return instance; }
		}

		protected MenuStyle() : base(PowerObject.PowerObjectParent, "MenuStyle", EnumeratedType.Instance) {
		}
	}
}
