// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class MenuItemType : HardwiredObject {
		static MenuItemType instance;

		static MenuItemType() {
			instance = new MenuItemType();
		}

		static public void Init() {
		}

		public static MenuItemType Instance {
			get { return instance; }
		}

		protected MenuItemType() : base(PowerObject.PowerObjectParent, "MenuItemType", EnumeratedType.Instance) {
		}
	}
}
