// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class MonCalDisplayState : HardwiredObject {
		static MonCalDisplayState instance;

		static MonCalDisplayState() {
			instance = new MonCalDisplayState();
		}

		static public void Init() {
		}

		public static MonCalDisplayState Instance {
			get { return instance; }
		}

		protected MonCalDisplayState() : base(PowerObject.PowerObjectParent, "MonCalDisplayState", EnumeratedType.Instance) {
		}
	}
}
