// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class OleFunctioncallType : HardwiredObject {
		static OleFunctioncallType instance;

		static OleFunctioncallType() {
			instance = new OleFunctioncallType();
		}

		static public void Init() {
		}

		public static OleFunctioncallType Instance {
			get { return instance; }
		}

		protected OleFunctioncallType() : base(PowerObject.PowerObjectParent, "OleFunctioncallType", EnumeratedType.Instance) {
		}
	}
}
