// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class OmActivateType : HardwiredObject {
		static OmActivateType instance;

		static OmActivateType() {
			instance = new OmActivateType();
		}

		static public void Init() {
		}

		public static OmActivateType Instance {
			get { return instance; }
		}

		protected OmActivateType() : base(PowerObject.PowerObjectParent, "OmActivateType", EnumeratedType.Instance) {
		}
	}
}
