// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class OmActivation : HardwiredObject {
		static OmActivation instance;

		static OmActivation() {
			instance = new OmActivation();
		}

		static public void Init() {
		}

		public static OmActivation Instance {
			get { return instance; }
		}

		protected OmActivation() : base(PowerObject.PowerObjectParent, "OmActivation", EnumeratedType.Instance) {
		}
	}
}
