// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class OmContentsAllowed : HardwiredObject {
		static OmContentsAllowed instance;

		static OmContentsAllowed() {
			instance = new OmContentsAllowed();
		}

		static public void Init() {
		}

		public static OmContentsAllowed Instance {
			get { return instance; }
		}

		protected OmContentsAllowed() : base(PowerObject.PowerObjectParent, "OmContentsAllowed", EnumeratedType.Instance) {
		}
	}
}
