// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class OsTypes : HardwiredObject {
		static OsTypes instance;

		static OsTypes() {
			instance = new OsTypes();
		}

		static public void Init() {
		}

		public static OsTypes Instance {
			get { return instance; }
		}

		protected OsTypes() : base(PowerObject.PowerObjectParent, "OsTypes", EnumeratedType.Instance) {
		}
	}
}
