// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class ParagraphSetting : HardwiredObject {
		static ParagraphSetting instance;

		static ParagraphSetting() {
			instance = new ParagraphSetting();
		}

		static public void Init() {
		}

		public static ParagraphSetting Instance {
			get { return instance; }
		}

		protected ParagraphSetting() : base(PowerObject.PowerObjectParent, "ParagraphSetting", EnumeratedType.Instance) {
		}
	}
}
