// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class ParmType : HardwiredObject {
		static ParmType instance;

		static ParmType() {
			instance = new ParmType();
		}

		static public void Init() {
		}

		public static ParmType Instance {
			get { return instance; }
		}

		protected ParmType() : base(PowerObject.PowerObjectParent, "ParmType", EnumeratedType.Instance) {
		}
	}
}
