// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Pointer : HardwiredObject {
		static Pointer instance;

		static Pointer() {
			instance = new Pointer();
		}

		static public void Init() {
		}

		public static Pointer Instance {
			get { return instance; }
		}

		protected Pointer() : base(PowerObject.PowerObjectParent, "Pointer", EnumeratedType.Instance) {
		}
	}
}
