// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class RowFocusInd : HardwiredObject {
		static RowFocusInd instance;

		static RowFocusInd() {
			instance = new RowFocusInd();
		}

		static public void Init() {
		}

		public static RowFocusInd Instance {
			get { return instance; }
		}

		protected RowFocusInd() : base(PowerObject.PowerObjectParent, "RowFocusInd", EnumeratedType.Instance) {
		}
	}
}
