// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class SaveMetaData : HardwiredObject {
		static SaveMetaData instance;

		static SaveMetaData() {
			instance = new SaveMetaData();
		}

		static public void Init() {
		}

		public static SaveMetaData Instance {
			get { return instance; }
		}

		protected SaveMetaData() : base(PowerObject.PowerObjectParent, "SaveMetaData", EnumeratedType.Instance) {
		}
	}
}
