// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class SaveAsType : HardwiredObject {
		static SaveAsType instance;

		static SaveAsType() {
			instance = new SaveAsType();
		}

		static public void Init() {
		}

		public static SaveAsType Instance {
			get { return instance; }
		}

		protected SaveAsType() : base(PowerObject.PowerObjectParent, "SaveAsType", EnumeratedType.Instance) {
		}
	}
}
