// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class ScriptKind : HardwiredObject {
		static ScriptKind instance;

		static ScriptKind() {
			instance = new ScriptKind();
		}

		static public void Init() {
		}

		public static ScriptKind Instance {
			get { return instance; }
		}

		protected ScriptKind() : base(PowerObject.PowerObjectParent, "ScriptKind", EnumeratedType.Instance) {
		}
	}
}
