// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class SeekType : HardwiredObject {
		static SeekType instance;

		static SeekType() {
			instance = new SeekType();
		}

		static public void Init() {
		}

		public static SeekType Instance {
			get { return instance; }
		}

		protected SeekType() : base(PowerObject.PowerObjectParent, "SeekType", EnumeratedType.Instance) {
		}
	}
}
