// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class SetPosType : HardwiredObject {
		static SetPosType instance;

		static SetPosType() {
			instance = new SetPosType();
		}

		static public void Init() {
		}

		public static SetPosType Instance {
			get { return instance; }
		}

		protected SetPosType() : base(PowerObject.PowerObjectParent, "SetPosType", EnumeratedType.Instance) {
		}
	}
}
