// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Spacing : HardwiredObject {
		static Spacing instance;

		static Spacing() {
			instance = new Spacing();
		}

		static public void Init() {
		}

		public static Spacing Instance {
			get { return instance; }
		}

		protected Spacing() : base(PowerObject.PowerObjectParent, "Spacing", EnumeratedType.Instance) {
		}
	}
}
