// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class SqlPreviewType : HardwiredObject {
		static SqlPreviewType instance;

		static SqlPreviewType() {
			instance = new SqlPreviewType();
		}

		static public void Init() {
		}

		public static SqlPreviewType Instance {
			get { return instance; }
		}

		protected SqlPreviewType() : base(PowerObject.PowerObjectParent, "SqlPreviewType", EnumeratedType.Instance) {
		}
	}
}
