// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class SqlPreviewFunction : HardwiredObject {
		static SqlPreviewFunction instance;

		static SqlPreviewFunction() {
			instance = new SqlPreviewFunction();
		}

		static public void Init() {
		}

		public static SqlPreviewFunction Instance {
			get { return instance; }
		}

		protected SqlPreviewFunction() : base(PowerObject.PowerObjectParent, "SqlPreviewFunction", EnumeratedType.Instance) {
		}
	}
}
