// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class TextCase : HardwiredObject {
		static TextCase instance;

		static TextCase() {
			instance = new TextCase();
		}

		static public void Init() {
		}

		public static TextCase Instance {
			get { return instance; }
		}

		protected TextCase() : base(PowerObject.PowerObjectParent, "TextCase", EnumeratedType.Instance) {
		}
	}
}
