// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class TextStyle : HardwiredObject {
		static TextStyle instance;

		static TextStyle() {
			instance = new TextStyle();
		}

		static public void Init() {
		}

		public static TextStyle Instance {
			get { return instance; }
		}

		protected TextStyle() : base(PowerObject.PowerObjectParent, "TextStyle", EnumeratedType.Instance) {
		}
	}
}
