// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class TimerKind : HardwiredObject {
		static TimerKind instance;

		static TimerKind() {
			instance = new TimerKind();
		}

		static public void Init() {
		}

		public static TimerKind Instance {
			get { return instance; }
		}

		protected TimerKind() : base(PowerObject.PowerObjectParent, "TimerKind", EnumeratedType.Instance) {
		}
	}
}
