// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class ToolBarAlignment : HardwiredObject {
		static ToolBarAlignment instance;

		static ToolBarAlignment() {
			instance = new ToolBarAlignment();
		}

		static public void Init() {
		}

		public static ToolBarAlignment Instance {
			get { return instance; }
		}

		protected ToolBarAlignment() : base(PowerObject.PowerObjectParent, "ToolBarAlignment", EnumeratedType.Instance) {
		}
	}
}
