// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class ToolBarStyle : HardwiredObject {
		static ToolBarStyle instance;

		static ToolBarStyle() {
			instance = new ToolBarStyle();
		}

		static public void Init() {
		}

		public static ToolBarStyle Instance {
			get { return instance; }
		}

		protected ToolBarStyle() : base(PowerObject.PowerObjectParent, "ToolBarStyle", EnumeratedType.Instance) {
		}
	}
}
