// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class TraceCategory : HardwiredObject {
		static TraceCategory instance;

		static TraceCategory() {
			instance = new TraceCategory();
		}

		static public void Init() {
		}

		public static TraceCategory Instance {
			get { return instance; }
		}

		protected TraceCategory() : base(PowerObject.PowerObjectParent, "TraceCategory", EnumeratedType.Instance) {
		}
	}
}
