// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class TraceActivity : HardwiredObject {
		static TraceActivity instance;

		static TraceActivity() {
			instance = new TraceActivity();
		}

		static public void Init() {
		}

		public static TraceActivity Instance {
			get { return instance; }
		}

		protected TraceActivity() : base(PowerObject.PowerObjectParent, "TraceActivity", EnumeratedType.Instance) {
		}
	}
}
