// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class TreeNavigation : HardwiredObject {
		static TreeNavigation instance;

		static TreeNavigation() {
			instance = new TreeNavigation();
		}

		static public void Init() {
		}

		public static TreeNavigation Instance {
			get { return instance; }
		}

		protected TreeNavigation() : base(PowerObject.PowerObjectParent, "TreeNavigation", EnumeratedType.Instance) {
		}
	}
}
