// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class UserObjects : HardwiredObject {
		static UserObjects instance;

		static UserObjects() {
			instance = new UserObjects();
		}

		static public void Init() {
		}

		public static UserObjects Instance {
			get { return instance; }
		}

		protected UserObjects() : base(PowerObject.PowerObjectParent, "UserObjects", EnumeratedType.Instance) {
		}
	}
}
