// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class ValSchemeType : HardwiredObject {
		static ValSchemeType instance;

		static ValSchemeType() {
			instance = new ValSchemeType();
		}

		static public void Init() {
		}

		public static ValSchemeType Instance {
			get { return instance; }
		}

		protected ValSchemeType() : base(PowerObject.PowerObjectParent, "ValSchemeType", EnumeratedType.Instance) {
		}
	}
}
