// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class VarAccess : HardwiredObject {
		static VarAccess instance;

		static VarAccess() {
			instance = new VarAccess();
		}

		static public void Init() {
		}

		public static VarAccess Instance {
			get { return instance; }
		}

		protected VarAccess() : base(PowerObject.PowerObjectParent, "VarAccess", EnumeratedType.Instance) {
		}
	}
}
