// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class VariableCardinalityType : HardwiredObject {
		static VariableCardinalityType instance;

		static VariableCardinalityType() {
			instance = new VariableCardinalityType();
		}

		static public void Init() {
		}

		public static VariableCardinalityType Instance {
			get { return instance; }
		}

		protected VariableCardinalityType() : base(PowerObject.PowerObjectParent, "VariableCardinalityType", EnumeratedType.Instance) {
		}
	}
}
