// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class VariableKind : HardwiredObject {
		static VariableKind instance;

		static VariableKind() {
			instance = new VariableKind();
		}

		static public void Init() {
		}

		public static VariableKind Instance {
			get { return instance; }
		}

		protected VariableKind() : base(PowerObject.PowerObjectParent, "VariableKind", EnumeratedType.Instance) {
		}
	}
}
