// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class VTextAlign : HardwiredObject {
		static VTextAlign instance;

		static VTextAlign() {
			instance = new VTextAlign();
		}

		static public void Init() {
		}

		public static VTextAlign Instance {
			get { return instance; }
		}

		protected VTextAlign() : base(PowerObject.PowerObjectParent, "VTextAlign", EnumeratedType.Instance) {
		}
	}
}
