// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class VTickMarks : HardwiredObject {
		static VTickMarks instance;

		static VTickMarks() {
			instance = new VTickMarks();
		}

		static public void Init() {
		}

		public static VTickMarks Instance {
			get { return instance; }
		}

		protected VTickMarks() : base(PowerObject.PowerObjectParent, "VTickMarks", EnumeratedType.Instance) {
		}
	}
}
