// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class WebPagingMethod : HardwiredObject {
		static WebPagingMethod instance;

		static WebPagingMethod() {
			instance = new WebPagingMethod();
		}

		static public void Init() {
		}

		public static WebPagingMethod Instance {
			get { return instance; }
		}

		protected WebPagingMethod() : base(PowerObject.PowerObjectParent, "WebPagingMethod", EnumeratedType.Instance) {
		}
	}
}
