// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class WeekDay : HardwiredObject {
		static WeekDay instance;

		static WeekDay() {
			instance = new WeekDay();
		}

		static public void Init() {
		}

		public static WeekDay Instance {
			get { return instance; }
		}

		protected WeekDay() : base(PowerObject.PowerObjectParent, "WeekDay", EnumeratedType.Instance) {
		}
	}
}
