// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class WindowState : HardwiredObject {
		static WindowState instance;

		static WindowState() {
			instance = new WindowState();
		}

		static public void Init() {
		}

		public static WindowState Instance {
			get { return instance; }
		}

		protected WindowState() : base(PowerObject.PowerObjectParent, "WindowState", EnumeratedType.Instance) {
		}
	}
}
