// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class WindowType : HardwiredObject {
		static WindowType instance;

		static WindowType() {
			instance = new WindowType();
		}

		static public void Init() {
		}

		public static WindowType Instance {
			get { return instance; }
		}

		protected WindowType() : base(PowerObject.PowerObjectParent, "WindowType", EnumeratedType.Instance) {
		}
	}
}
