// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class WriteMode : HardwiredObject {
		static WriteMode instance;

		static WriteMode() {
			instance = new WriteMode();
		}

		static public void Init() {
		}

		public static WriteMode Instance {
			get { return instance; }
		}

		protected WriteMode() : base(PowerObject.PowerObjectParent, "WriteMode", EnumeratedType.Instance) {
		}
	}
}
