// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class AdoResultSet : HardwiredObject {
		static AdoResultSet instance;

		static AdoResultSet() {
			instance = new AdoResultSet();
		}

		static public void Init() {
		}

		public static AdoResultSet Instance {
			get { return instance; }
		}

		protected AdoResultSet() : base(PowerObject.PowerObjectParent, "AdoResultSet", ResultSet.Instance) {
		}
	}
}
