// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Connection : HardwiredObject {
		static Connection instance;

		static Connection() {
			instance = new Connection();
		}

		static public void Init() {
		}

		public static Connection Instance {
			get { return instance; }
		}

		protected Connection() : base(PowerObject.PowerObjectParent, "Connection", ConnectObject.Instance) {
		}
	}
}
