// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class ContextInformation : HardwiredObject {
		static ContextInformation instance;

		static ContextInformation() {
			instance = new ContextInformation();
		}

		static public void Init() {
		}

		public static ContextInformation Instance {
			get { return instance; }
		}

		protected ContextInformation() : base(PowerObject.PowerObjectParent, "ContextInformation", Service.Instance) {
		}
	}
}
