// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class ContextKeyword : HardwiredObject {
		static ContextKeyword instance;

		static ContextKeyword() {
			instance = new ContextKeyword();
		}

		static public void Init() {
		}

		public static ContextKeyword Instance {
			get { return instance; }
		}

		protected ContextKeyword() : base(PowerObject.PowerObjectParent, "ContextKeyword", Service.Instance) {
		}
	}
}
