// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class CPlusPlus : HardwiredObject {
		static CPlusPlus instance;

		static CPlusPlus() {
			instance = new CPlusPlus();
		}

		static public void Init() {
		}

		public static CPlusPlus Instance {
			get { return instance; }
		}

		protected CPlusPlus() : base(PowerObject.PowerObjectParent, "CPlusPlus", NonVisualObject.Instance) {
		}
	}
}
