// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class DataStore : HardwiredObject {
		static DataStore instance;

		static DataStore() {
			instance = new DataStore();
		}

		static public void Init() {
		}

		public static DataStore Instance {
			get { return instance; }
		}

		protected DataStore() : base(PowerObject.PowerObjectParent, "DataStore", NonVisualObject.Instance) {
		}
	}
}
