// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class DWObject : HardwiredObject {
		static DWObject instance;

		static DWObject() {
			instance = new DWObject();
		}

		static public void Init() {
		}

		public static DWObject Instance {
			get { return instance; }
		}

		protected DWObject() : base(PowerObject.PowerObjectParent, "DWObject", ExtObject.Instance) {
		}
	}
}
