// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class DynamicDescriptionArea : HardwiredObject {
		static DynamicDescriptionArea instance;

		static DynamicDescriptionArea() {
			instance = new DynamicDescriptionArea();
		}

		static public void Init() {
		}

		public static DynamicDescriptionArea Instance {
			get { return instance; }
		}

		protected DynamicDescriptionArea() : base(PowerObject.PowerObjectParent, "DynamicDescriptionArea", NonVisualObject.Instance) {
		}
	}
}
