// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class ExtObject : HardwiredObject {
		static ExtObject instance;

		static ExtObject() {
			instance = new ExtObject();
		}

		static public void Init() {
		}

		public static ExtObject Instance {
			get { return instance; }
		}

		protected ExtObject() : base(PowerObject.PowerObjectParent, "ExtObject", NonVisualObject.Instance) {
		}
	}
}
