// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class INet : HardwiredObject {
		static INet instance;

		static INet() {
			instance = new INet();
		}

		static public void Init() {
		}

		public static INet Instance {
			get { return instance; }
		}

		protected INet() : base(PowerObject.PowerObjectParent, "INet", Service.Instance) {
		}
	}
}
