// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class InternetResult : HardwiredObject {
		static InternetResult instance;

		static InternetResult() {
			instance = new InternetResult();
		}

		static public void Init() {
		}

		public static InternetResult Instance {
			get { return instance; }
		}

		protected InternetResult() : base(PowerObject.PowerObjectParent, "InternetResult", NonVisualObject.Instance) {
		}
	}
}
