// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Message : HardwiredObject {
		static Message instance;

		static Message() {
			instance = new Message();
		}

		static public void Init() {
		}

		public static Message Instance {
			get { return instance; }
		}

		protected Message() : base(PowerObject.PowerObjectParent, "Message", NonVisualObject.Instance) {
		}
	}
}
