// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class OleObject : HardwiredObject {
		static OleObject instance;

		static OleObject() {
			instance = new OleObject();
		}

		static public void Init() {
		}

		public static OleObject Instance {
			get { return instance; }
		}

		protected OleObject() : base(PowerObject.PowerObjectParent, "OleObject", OMObject.Instance) {
		}
	}
}
