// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class OleStream : HardwiredObject {
		static OleStream instance;

		static OleStream() {
			instance = new OleStream();
		}

		static public void Init() {
		}

		public static OleStream Instance {
			get { return instance; }
		}

		protected OleStream() : base(PowerObject.PowerObjectParent, "OleStream", OmStream.Instance) {
		}
	}
}
