// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class OMObject : HardwiredObject {
		static OMObject instance;

		static OMObject() {
			instance = new OMObject();
		}

		static public void Init() {
		}

		public static OMObject Instance {
			get { return instance; }
		}

		protected OMObject() : base(PowerObject.PowerObjectParent, "OMObject", ExtObject.Instance) {
		}
	}
}
