// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class OmStorage : HardwiredObject {
		static OmStorage instance;

		static OmStorage() {
			instance = new OmStorage();
		}

		static public void Init() {
		}

		public static OmStorage Instance {
			get { return instance; }
		}

		protected OmStorage() : base(PowerObject.PowerObjectParent, "OmStorage", NonVisualObject.Instance) {
		}
	}
}
