// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Orb : HardwiredObject {
		static Orb instance;

		static Orb() {
			instance = new Orb();
		}

		static public void Init() {
		}

		public static Orb Instance {
			get { return instance; }
		}

		protected Orb() : base(PowerObject.PowerObjectParent, "Orb", NonVisualObject.Instance) {
		}
	}
}
