// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Pipeline : HardwiredObject {
		static Pipeline instance;

		static Pipeline() {
			instance = new Pipeline();
		}

		static public void Init() {
		}

		public static Pipeline Instance {
			get { return instance; }
		}

		protected Pipeline() : base(PowerObject.PowerObjectParent, "Pipeline", NonVisualObject.Instance) {
		}
	}
}
