// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class RemoteObject : HardwiredObject {
		static RemoteObject instance;

		static RemoteObject() {
			instance = new RemoteObject();
		}

		static public void Init() {
		}

		public static RemoteObject Instance {
			get { return instance; }
		}

		protected RemoteObject() : base(PowerObject.PowerObjectParent, "RemoteObject", NonVisualObject.Instance) {
		}
	}
}
