// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Service : HardwiredObject {
		static Service instance;

		static Service() {
			instance = new Service();
		}

		static public void Init() {
		}

		public static Service Instance {
			get { return instance; }
		}

		protected Service() : base(PowerObject.PowerObjectParent, "Service", NonVisualObject.Instance) {
		}
	}
}
