// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class SSLCallback : HardwiredObject {
		static SSLCallback instance;

		static SSLCallback() {
			instance = new SSLCallback();
		}

		static public void Init() {
		}

		public static SSLCallback Instance {
			get { return instance; }
		}

		protected SSLCallback() : base(PowerObject.PowerObjectParent, "SSLCallback", NonVisualObject.Instance) {
		}
	}
}
