// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class SSLServiceProvider : HardwiredObject {
		static SSLServiceProvider instance;

		static SSLServiceProvider() {
			instance = new SSLServiceProvider();
		}

		static public void Init() {
		}

		public static SSLServiceProvider Instance {
			get { return instance; }
		}

		protected SSLServiceProvider() : base(PowerObject.PowerObjectParent, "SSLServiceProvider", Service.Instance) {
		}
	}
}
