// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Timing : HardwiredObject {
		static Timing instance;

		static Timing() {
			instance = new Timing();
		}

		static public void Init() {
		}

		public static Timing Instance {
			get { return instance; }
		}

		protected Timing() : base(PowerObject.PowerObjectParent, "Timing", NonVisualObject.Instance) {
		}
	}
}
