// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Environment : HardwiredObject {
		static Environment instance;

		static Environment() {
			instance = new Environment();
		}

		static public void Init() {
		}

		public static Environment Instance {
			get { return instance; }
		}

		protected Environment() : base(PowerObject.PowerObjectParent, "Environment", Structure.Instance) {
		}
	}
}
