// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class MailFileDescription : HardwiredObject {
		static MailFileDescription instance;

		static MailFileDescription() {
			instance = new MailFileDescription();
		}

		static public void Init() {
		}

		public static MailFileDescription Instance {
			get { return instance; }
		}

		protected MailFileDescription() : base(PowerObject.PowerObjectParent, "MailFileDescription", Structure.Instance) {
		}
	}
}
