// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class MailRecipient : HardwiredObject {
		static MailRecipient instance;

		static MailRecipient() {
			instance = new MailRecipient();
		}

		static public void Init() {
		}

		public static MailRecipient Instance {
			get { return instance; }
		}

		protected MailRecipient() : base(PowerObject.PowerObjectParent, "MailRecipient", Structure.Instance) {
		}
	}
}
