// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class Structure : HardwiredObject {
		static Structure instance;

		static Structure() {
			instance = new Structure();
		}

		static public void Init() {
		}

		public static Structure Instance {
			get { return instance; }
		}

		protected Structure() : base(PowerObject.PowerObjectParent, "Structure", PowerObject.PowerObjectInstance) {
		}
	}
}
