// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class TreeViewItem : HardwiredObject {
		static TreeViewItem instance;

		static TreeViewItem() {
			instance = new TreeViewItem();
		}

		static public void Init() {
		}

		public static TreeViewItem Instance {
			get { return instance; }
		}

		protected TreeViewItem() : base(PowerObject.PowerObjectParent, "TreeViewItem", Structure.Instance) {
		}
	}
}
