// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class TraceError : HardwiredObject {
		static TraceError instance;

		static TraceError() {
			instance = new TraceError();
		}

		static public void Init() {
		}

		public static TraceError Instance {
			get { return instance; }
		}

		protected TraceError() : base(PowerObject.PowerObjectParent, "TraceError", TraceActivityNode.Instance) {
		}
	}
}
