// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class TraceObject : HardwiredObject {
		static TraceObject instance;

		static TraceObject() {
			instance = new TraceObject();
		}

		static public void Init() {
		}

		public static TraceObject Instance {
			get { return instance; }
		}

		protected TraceObject() : base(PowerObject.PowerObjectParent, "TraceObject", TraceActivityNode.Instance) {
		}
	}
}
