// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class TraceActivityNode : HardwiredObject {
		static TraceActivityNode instance;

		static TraceActivityNode() {
			instance = new TraceActivityNode();
		}

		static public void Init() {
		}

		public static TraceActivityNode Instance {
			get { return instance; }
		}

		protected TraceActivityNode() : base(PowerObject.PowerObjectParent, "TraceActivityNode", PowerObject.PowerObjectInstance) {
		}
	}
}
