// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class TraceBeginEnd : HardwiredObject {
		static TraceBeginEnd instance;

		static TraceBeginEnd() {
			instance = new TraceBeginEnd();
		}

		static public void Init() {
		}

		public static TraceBeginEnd Instance {
			get { return instance; }
		}

		protected TraceBeginEnd() : base(PowerObject.PowerObjectParent, "TraceBeginEnd", TraceActivityNode.Instance) {
		}
	}
}
