// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class TraceUser : HardwiredObject {
		static TraceUser instance;

		static TraceUser() {
			instance = new TraceUser();
		}

		static public void Init() {
		}

		public static TraceUser Instance {
			get { return instance; }
		}

		protected TraceUser() : base(PowerObject.PowerObjectParent, "TraceUser", TraceActivityNode.Instance) {
		}
	}
}
