// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class TraceSQL : HardwiredObject {
		static TraceSQL instance;

		static TraceSQL() {
			instance = new TraceSQL();
		}

		static public void Init() {
		}

		public static TraceSQL Instance {
			get { return instance; }
		}

		protected TraceSQL() : base(PowerObject.PowerObjectParent, "TraceSQL", TraceActivityNode.Instance) {
		}
	}
}
