// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class TraceRoutine : HardwiredObject {
		static TraceRoutine instance;

		static TraceRoutine() {
			instance = new TraceRoutine();
		}

		static public void Init() {
		}

		public static TraceRoutine Instance {
			get { return instance; }
		}

		protected TraceRoutine() : base(PowerObject.PowerObjectParent, "TraceRoutine", TraceActivityNode.Instance) {
		}
	}
}
