// This code was autogenerated.
// Changes to this file will be lost if the file is regenerated.
using System;
namespace PowerDoc.PowerObjects {
	public class TraceLine : HardwiredObject {
		static TraceLine instance;

		static TraceLine() {
			instance = new TraceLine();
		}

		static public void Init() {
		}

		public static TraceLine Instance {
			get { return instance; }
		}

		protected TraceLine() : base(PowerObject.PowerObjectParent, "TraceLine", TraceActivityNode.Instance) {
		}
	}
}
